### ISSUE TITLE
About qdrant

### ISSUE THREAD

**Issue by Murphy1227** [brucepro/Memoir#16]
I'm having problems related to installing and makingv theqdrant work, I've never really used them and I have no idea how to configure it, It would be great if there was a tutorial on YouTube or something like that on how to configure the memoir extension without using docker.

**Comment by Belarrius1** [comment]
Hi,

I'm on Linux Mint, can you tell me what to comment in script.py? I downloaded "qdrant" binaries for linux and put in "text-generation-webui/extensions/Memoir"

Thanks for advance

**Comment by Murphy1227** [comment]
i had this error: 
Traceback (most recent call last):
  File "E:\IA\Texto\Oobabooga\text-generation-webui\modules\extensions.py", line 37, in load_extensions
    extension = importlib.import_module(f"extensions.{name}.script")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IA\Texto\Oobabooga\text-generation-webui\installer_files\env\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IA\Texto\Oobabooga\text-generation-webui\extensions\Memoir\script.py", line 23, in <module>
    from python_on_whales import DockerClient
ModuleNotFoundError: No module named 'python_on_whales'
