### ISSUE TITLE
"Python_on_Whale

### ISSUE THREAD

**Issue by Murphy1227** [brucepro/Memoir#18]
i'm having this error, can anyone help me?

i had this error:
Traceback (most recent call last):
File "E:\IA\Texto\Oobabooga\text-generation-webui\modules\extensions.py", line 37, in load_extensions
extension = importlib.import_module(f"extensions.{name}.script")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\IA\Texto\Oobabooga\text-generation-webui\installer_files\env\Lib\importlib_init_.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 1204, in _gcd_import
File "", line 1176, in _find_and_load
File "", line 1147, in _find_and_load_unlocked
File "", line 690, in _load_unlocked
File "", line 940, in exec_module
File "", line 241, in _call_with_frames_removed
File "E:\IA\Texto\Oobabooga\text-generation-webui\extensions\Memoir\script.py", line 23, in
from python_on_whales import DockerClient
ModuleNotFoundError: No module named 'python_on_whales'

**Comment by Murphy1227** [comment]
i am running without the docker, how should i fix it?

**Comment by Murphy1227** [comment]
Now i am having this error XD:

  File "E:\IA\Texto\Oobabooga\text-generation-webui\modules\extensions.py", line 37, in load_extensions
    extension = importlib.import_module(f"extensions.{name}.script")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IA\Texto\Oobabooga\text-generation-webui\installer_files\env\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IA\Texto\Oobabooga\text-generation-webui\extensions\Memoir\script.py", line 12, in <module>
    from extensions.Memoir.commandhandler import CommandHandler
  File "E:\IA\Texto\Oobabooga\text-generation-webui\extensions\Memoir\commandhandler.py", line 6, in <module>
    from extensions.Memoir.persona.persona import Persona
  File "E:\IA\Texto\Oobabooga\text-generation-webui\extensions\Memoir\persona\persona.py", line 4, in <module>
    from textblob import TextBlob
ModuleNotFoundError: No module named 'textblob'

**Comment by Murphy1227** [comment]
This extension should have 2 different downloads, one configured for docker and the other without @_@

**Comment by Murphy1227** [comment]
Bruh, its just error after error ;-; 

Traceback (most recent call last):
  File "E:\IA\Texto\Oobabooga\text-generation-webui\modules\extensions.py", line 37, in load_extensions
    extension = importlib.import_module(f"extensions.{name}.script")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IA\Texto\Oobabooga\text-generation-webui\installer_files\env\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IA\Texto\Oobabooga\text-generation-webui\extensions\Memoir\script.py", line 20, in <module>
    current_dir = os.path.dirname(os.path.abspath(__file__))
                  ^^
NameError: name 'os' is not defined

**Comment by Murphy1227** [comment]
i already did this @_@ 2 times

**Comment by Murphy1227** [comment]
YES

**Comment by Murphy1227** [comment]
the cmd_windows.bat right?

**Comment by Murphy1227** [comment]
Okay, i will try.

**Comment by Murphy1227** [comment]
i still having the same problem, how do i pip install the OS? its not installing it...

pip install OS
ERROR: Could not find a version that satisfies the requirement OS (from versions: none)
ERROR: No matching distribution found for OS

and after that i installed the requiriments manually it still the same:

Traceback (most recent call last):
  File "E:\IA\Texto\Oobabooga\text-generation-webui\modules\extensions.py", line 37, in load_extensions
    extension = importlib.import_module(f"extensions.{name}.script")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IA\Texto\Oobabooga\text-generation-webui\installer_files\env\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IA\Texto\Oobabooga\text-generation-webui\extensions\Memoir\script.py", line 19, in <module>
    current_dir = os.path.dirname(os.path.abspath(__file__))
                  ^^
NameError: name 'os' is not defined

**Comment by wardensc2** [comment]
Hi I just do the fresh install of Textgen webui. Update everything, install Memoir+ requirement in venv, install every requirements in update wizard now Memoir+ require Docker have more privileges. What should I do, I already am admin user:

Please check this log

![image](https://github.com/brucepro/Memoir/assets/77379748/d4c414de-f525-4d8c-b09b-39a9e979c42d)
