### ISSUE TITLE
[WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by matrixfox** [brucepro/Memoir#19]
Run 'docker COMMAND --help' for more information on a command.

To get more help with docker, check out our guides at https://docs.docker.com/go/guides/

: Error C:\Users\Joel\Documents\GitHub\text-generation-webui\extensions\Memoir\qdrant-docker-compose.yml: The docker command executed was `C:\Users\Joel\.cache\python-on-whales\docker-cli\20.10.5\docker compose --file C:\Users\Joel\Documents\GitHub\text-generation-webui\extensions\Memoir\qdrant-docker-compose.yml up --detach`.
It returned with code 125
The content of stdout can be found above the stacktrace (it wasn't captured).
The content of stderr can be found above the stacktrace (it wasn't captured).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    raise exc from None
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\httpcore\_sync\connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\httpcore\_backends\sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\qdrant_client\http\api_client.py", line 101, in send_inner
    response = self._client.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\httpx\_transports\default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\gradio\utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\modules\chat.py", line 405, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True, for_ui=True)):
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\modules\chat.py", line 373, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message, for_ui=for_ui):
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\modules\chat.py", line 275, in chatbot_wrapper
    text = apply_extensions('input', text, state, is_chat=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\modules\extensions.py", line 231, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\modules\extensions.py", line 89, in _apply_string_extensions
    text = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\extensions\Memoir\script.py", line 208, in input_modifier
    params['user_long_term_memories'] = ltm.recall(string)
                                        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\extensions\Memoir\memory\long_term_memory.py", line 95, in recall
    results = self.qdrant.search(
              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\qdrant_client\qdrant_client.py", line 345, in search
    return self._client.search(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\qdrant_client\qdrant_remote.py", line 479, in search
    search_result = self.http.points_api.search_points(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\qdrant_client\http\api\points_api.py", line 1388, in search_points
    return self._build_for_search_points(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\qdrant_client\http\api\points_api.py", line 636, in _build_for_search_points
    return self.api_client.request(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\qdrant_client\http\api_client.py", line 74, in request
    return self.send(request, type_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\qdrant_client\http\api_client.py", line 91, in send
    response = self.middleware(request, self.send_inner)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\qdrant_client\http\api_client.py", line 200, in __call__
    return call_next(request)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joel\Documents\GitHub\text-generation-webui\installer_files\env\Lib\site-packages\qdrant_client\http\api_client.py", line 103, in send_inner
    raise ResponseHandlingException(e)
qdrant_client.http.exceptions.ResponseHandlingException: [WinError 10061] No connection could be made because the target machine actively refused it

wtf does that mean? I'm seriously regretting restoring my machine...

**Comment by PRCbubu** [comment]
I'm also facing the same problem @brucepro

**Comment by PRCbubu** [comment]
What is qdrant dashboard ? I'm sorry but I'm kinda dumb and clueless! If possible, please help me in an easy way. @brucepro

**Comment by PRCbubu** [comment]
![image](https://github.com/brucepro/Memoir/assets/93852561/dbab021e-c01a-4983-b66e-f28de8e1612f)
Do you mean this @brucepro ?

**Comment by PRCbubu** [comment]
`23:28:00-589199 INFO     Loading the extension "Memoir"
unknown flag: --file
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default
                           "C:\\Users\\PRCbu\\.docker")
  -c, --context string     Name of the context to use to connect to the
                           daemon (overrides DOCKER_HOST env var and
                           default context set with "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level
                           ("debug"|"info"|"warn"|"error"|"fatal")
                           (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default
                           "C:\\Users\\PRCbu\\.docker\\ca.pem")
      --tlscert string     Path to TLS certificate file (default
                           "C:\\Users\\PRCbu\\.docker\\cert.pem")
      --tlskey string      Path to TLS key file (default
                           "C:\\Users\\PRCbu\\.docker\\key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  builder     Manage builds
  config      Manage Docker configs
  container   Manage containers
  context     Manage contexts
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  build       Build an image from a Dockerfile
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  images      List images
  import      Import the contents from a tarball to create a filesystem image
  info        Display system-wide information
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  run         Run a command in a new container
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  search      Search the Docker Hub for images
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  version     Show the Docker version information
  wait        Block until one or more containers stop, then print their exit codes

Run 'docker COMMAND --help' for more information on a command.

To get more help with docker, check out our guides at https://docs.docker.com/go/guides/

: Error D:\StableDiffution\text-generation-webui\extensions\Memoir\qdrant-docker-compose.yml: The docker command executed was `C:\Users\PRCbu\.cache\python-on-whales\docker-cli\20.10.5\docker compose --file D:\StableDiffution\text-generation-webui\extensions\Memoir\qdrant-docker-compose.yml up --detach`.
It returned with code 125
The content of stdout can be found above the stacktrace (it wasn't captured).
The content of stderr can be found above the stacktrace (it wasn't captured).`

Also, this is the thing that first shows up when I start the Textgen AI

**Comment by PRCbubu** [comment]
![image](https://github.com/brucepro/Memoir/assets/93852561/80883afb-2ecf-49b1-a30b-4e9377417e72)
This is what it is coming
@brucepro

**Comment by PRCbubu** [comment]
> In next release I will include a few qdrant options that don't require docker as many seem to have problems with it. Did you try installing docker desktop? It tends to simplify things.

No, I don't have docker installed in my laptop
