### ISSUE TITLE
Does this extension still work ?

### ISSUE THREAD

**Issue by Tum1370** [brucepro/Memoir#75]
As the title says, Does the Memoir extension still work on the latest oobobooga version?

I have only just instslled oobabooga a few days ago, Got it working fine with models, and installed AllTalk v2 extension which also works fine.
Now i am trying to add this memory addon, but i run in to errors, and it does not work.

I have installed Windows Docker (Not sure what else to do with this, but it is installed, and running when i try oobabooga with the Memoir extension.)
I have run the update wizard for oobabooga and selected the Memoir extension.
When the wizard runs, it does have an error message in red colour.

"**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
unstructured-client 0.28.1 requires aiofiles>=24.1.0, but you have aiofiles 23.2.1 which is incompatible.
unstructured-client 0.28.1 requires pydantic<2.10.0,>=2.9.2, but you have pydantic 2.8.2 which is incompatible."**

Can you please help ,and assist to get this extension working, or is the problem, its just out of date now ? and will not work ?

**Comment by Tum1370** [comment]
Thanks for your reply.  I have run the "update_wizard_windows" in the main oobabooga folder, and selected to update Memoir.
Thats what created those error messages ?
How do i "remove the version behind aiofiles" please ?

**Comment by Tum1370** [comment]
I see the Memoir extension at the bottom of my CHAT window, BUt whenever i send a message (even just Hello) to the AI, i see many errors in the oobabooga console window.

Could this be because i dont have qdrant even installed ? I have docker windows installed but have no idead what to do with it.

These are the messages in oobabooga window when i ask AI "Hello"

_Traceback (most recent call last):
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\httpx\_transports\default.py", line 250, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\httpcore\_sync\connection_pool.py", line 256, in handle_request
    raise exc from None
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\httpcore\_sync\connection_pool.py", line 236, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\httpcore\_sync\connection.py", line 101, in handle_request
    raise exc
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\httpcore\_sync\connection.py", line 78, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\httpcore\_sync\connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\httpcore\_backends\sync.py", line 207, in connect_tcp
    with map_exceptions(exc_map):
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\qdrant_client\http\api_client.py", line 106, in send_inner
    response = self._client.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\httpx\_client.py", line 1014, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\httpx\_transports\default.py", line 249, in handle_request
    with map_httpcore_exceptions():
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\httpx\_transports\default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1350, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 583, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 576, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 559, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 742, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\modules\chat.py", line 436, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True, for_ui=True)):
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\modules\chat.py", line 403, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message, for_ui=for_ui):
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\modules\chat.py", line 314, in chatbot_wrapper
    text = apply_extensions('input', text, state, is_chat=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\modules\extensions.py", line 231, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\modules\extensions.py", line 89, in _apply_string_extensions
    text = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\extensions\Memoir\script.py", line 216, in input_modifier
    params['user_long_term_memories'] = ltm.recall(string)
                                        ^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\extensions\Memoir\memory\long_term_memory.py", line 103, in recall
    results = self.qdrant.search(
              ^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\qdrant_client\qdrant_client.py", line 387, in search
    return self._client.search(
           ^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\qdrant_client\qdrant_remote.py", line 563, in search
    search_result = self.http.points_api.search_points(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\qdrant_client\http\api\points_api.py", line 1820, in search_points
    return self._build_for_search_points(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\qdrant_client\http\api\points_api.py", line 852, in _build_for_search_points
    return self.api_client.request(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\qdrant_client\http\api_client.py", line 79, in request
    return self.send(request, type_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\qdrant_client\http\api_client.py", line 96, in send
    response = self.middleware(request, self.send_inner)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\qdrant_client\http\api_client.py", line 205, in __call__
    return call_next(request)
           ^^^^^^^^^^^^^^^^^^
  File "M:\Software\AI_Tools\oobabooga\text-generation-webui-main\installer_files\env\Lib\site-packages\qdrant_client\http\api_client.py", line 108, in send_inner
    raise ResponseHandlingException(e)
qdrant_client.http.exceptions.ResponseHandlingException: [WinError 10061] No connection could be made because the target machine actively refused it_

**Comment by Tum1370** [comment]
As soon as i untick Memoir in the Session section, The AI starts to work fine again. And repsonding.

**Comment by Tum1370** [comment]
OK i have got a little bit firther with this extension.
While i had Windows Docker opened, i opened a command prompt and typed the command "docker pull qdrant/qdrant"
Which seemed to install something.

Now when i start oobabooga, select the Memoir extenstion, and go to chat, i actually get a respsonse from the AI.
THe problem now is, The AI repeated itself saying the identical words the 5 times i tried asking it something.

I am not sure whether i have miseed something, or this is something else going wrong now ?

**Comment by Tum1370** [comment]
Ok that repeating was only in the first instance. Now after having a few more conversaton, i do not get the repeating.
But i also dont understand how the memory works. 
I tried telling the AI my name, but then in a new chat it did not know my name etc.

Whats actually going on with the memories, and how do you get each character to remember ?

**Comment by Tum1370** [comment]
NIce, thank you for the help.
I set the qdrant dashboard as a windows app, and can see 4 memories been stored at present.
Am not sure how the character calls on the information at present, Does it actually know the stuff that it records in the database ?
So in a new CHAT window, it would remember some of the summaries that were saved to the database etc ?

Its going to be really nice if this is how the addon works. I hope you keep working on it as this is a very good idea.

**Comment by Tum1370** [comment]
Thank you for your explanation. At the moment i have left the settings dafault, and just testing it, letting it build up memories to see how it changes responses etc.
I only started looking in to LLMs about a week ago. I watched a video of setting one locally up using oobabooga, thats why i have chosen this one.
I have just had a search of llama cpp, and it seem more complicated, and tailor towards programmers ?

In the week i have been experimenting with oobabooga, i have figure out models and model sizes etc, i have been sticking with GGUF models. I am using the Nemomix Unleashed at present, and have also got Qwen2.5 coder installed, as i would like to use the local LLM to help mean learn coding. (this will happen when i can get everything working as i would like with a chat bot at first)

Ive installed AllTalkv2, and got my own voice from a movie installed and working now. I have been using the new Windows 11 Voice Typing to type my responses to the LLM which works amazing. And now hopefully got a memory system installed. 
I am finding this all really interesting and exciting to play around with. I just hope the support continues for oobabooga and its extensions.
